// Generated by https://quicktype.io

export interface BooksProps {
  id: number;
  libro: string;
  titulo_original: string;
  fecha_de_lanzamiento: string;
  autora: string;
  descripcion: string;
}
