import { Metadata } from "next";
import { notFound } from "next/navigation"
import Image from 'next/image'

import { IoArrowRedoSharp, IoBalloonSharp } from "react-icons/io5";


// Generated by https://quicktype.io

export interface Character {
    id: string;
    name: string;
    alternate_names: string[];
    species: string;
    gender: string;
    house: string;
    dateOfBirth: string;
    yearOfBirth: number;
    wizard: boolean;
    ancestry: string;
    eyeColour: string;
    hairColour: string;
    wand: Wand;
    patronus: string;
    hogwartsStudent: boolean;
    hogwartsStaff: boolean;
    actor: string;
    alternate_actors: any[];
    alive: boolean;
    image: string;
}

export interface Wand {
    wood: string;
    core: string;
    length: number;
}


interface Props {
    params: { id: string };
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    try {
        const { name, house } = await getCharacterById(params.id);

        return {
            title: `${name} - ${house}`,
            description: `Space of ${name}`
        }
    } catch (error) {
        return {
            title: 'Character Page',
            description: "Character Description"
        }
    }
}

const getCharacterById = async (id: string): Promise<Character> => {
    try {
        const character = await fetch(`https://hp-api.onrender.com/api/character/${id}`)
            .then(resp => resp.json());
        console.log(character[0])
        return character[0];
    } catch (error) {
        notFound()
    }

}

export default async function CharacterPage({ params }: Props) {

    const character = await getCharacterById(params.id);
    const { name, house, patronus, alternate_names } = character;

    return (
        <div className="flex flex-col items-center bg-slate-400 w-full h-screen p-4">
            <Image src={character.image} width={250} height={100} alt={name} className="rounded-md" />
            <p className="font-bold text-2xl flex mt-2 ml-2"> <IoArrowRedoSharp /> <span className="text-gray-800">Name - {name}</span></p>
            <p className="font-bold text-2xl flex mt-2 ml-2"> <IoArrowRedoSharp /> <span className="text-gray-800">House - {house}</span></p>
            <p className="font-bold text-2xl flex mt-2 ml-2"> <IoArrowRedoSharp /> <span className="text-gray-800">Patronus -  {patronus}</span></p>
            <div className="flex flex-wrap items-center justify-center bg-green-500 p-4 rounded-xl">
                {
                    character.alternate_names?.map(name => (
                        <p key={character.id} className="mr-2 capitalize text-2xl font-bold text-center flex"> <IoBalloonSharp /> {name} </p>
                    ))
                }
            </div>
        </div>
    )
}