import { Metadata } from "next";
import { notFound } from "next/navigation"
import Image from 'next/image'

import { IoArrowRedoSharp, IoBalloonSharp } from "react-icons/io5";
import Link from "next/link";


// Generated by https://quicktype.io

export interface Character {
    id: string;
    name: string;
    alternate_names: string[];
    species: string;
    gender: string;
    house: string;
    dateOfBirth: string;
    yearOfBirth: number;
    wizard: boolean;
    ancestry: string;
    eyeColour: string;
    hairColour: string;
    wand: Wand;
    patronus: string;
    hogwartsStudent: boolean;
    hogwartsStaff: boolean;
    actor: string;
    alternate_actors: any[];
    alive: boolean;
    image: string;
}

export interface Wand {
    wood: string;
    core: string;
    length: number;
}


interface Props {
    params: { id: string };
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    try {
        const { name, house } = await getCharacterById(params.id);

        return {
            title: `${name} - ${house}`,
            description: `Space of ${name}`
        }
    } catch (error) {
        return {
            title: 'Character Page',
            description: "Character Description"
        }
    }
}

const getCharacterById = async (id: string): Promise<Character> => {
    try {
        const character = await fetch(`https://hp-api.onrender.com/api/character/${id}`)
            .then(resp => resp.json());

        return character[0];
    } catch (error) {
        notFound()
    }

}

export default async function CharacterPage({ params }: Props) {

    const character = await getCharacterById(params.id);
    const { name, house, patronus, actor } = character;

    return (
        <div className="flex flex-col items-center bg-slate-400 w-screen h-screen p-2">
            <Image src={character.image} width={250} height={100} alt={name} className="rounded-md" />
            <p className="font-bold text-2xl flex mt-2 ml-2"> <IoArrowRedoSharp /> <span className="text-gray-800">Name - {name}</span></p>
            {house && <p className="font-bold text-2xl flex mt-2 ml-2"> <IoArrowRedoSharp /> <span className="text-gray-800">House - {house}</span></p>}
            {patronus && <p className="font-bold text-2xl flex mt-2 ml-2"> <IoArrowRedoSharp /> <span className="text-gray-800">Patronus -  {patronus}</span></p>}
            {actor && <p className="font-bold text-2xl flex mt-2 ml-2"> <IoArrowRedoSharp /> <span className="text-gray-800">Actor  -  {actor}</span></p>}


            <Link href={'/dashboard/characters'} className="font-bold w-40 bg-red-400 text-center mt-2 p-2 rounded-lg hover:cursor-pointer hover:bg-blue-400 trannsition-all duration-500">Go Home</Link>
        </div>
    )
}