import { Metadata } from "next";
import { notFound } from "next/navigation"
import Image from 'next/image'
import { IoArrowRedoSharp } from "react-icons/io5";
import Link from "next/link";


// Generated by https://quicktype.io

export interface Character {
    id: string;
    name: string;
    alternate_names: string[];
    species: string;
    gender: string;
    house: string;
    dateOfBirth: string;
    yearOfBirth: number;
    wizard: boolean;
    ancestry: string;
    eyeColour: string;
    hairColour: string;
    wand: Wand;
    patronus: string;
    hogwartsStudent: boolean;
    hogwartsStaff: boolean;
    actor: string;
    alternate_actors: any[];
    alive: boolean;
    image: string;
}

export interface Wand {
    wood: string;
    core: string;
    length: number;
}


interface Props {
    params: { id: string };
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    try {
        const { name, house } = await getCharacterById(params.id);

        return {
            title: `${name} - ${house}`,
            description: `Space of ${name}`
        }
    } catch (error) {
        return {
            title: 'Character Page',
            description: "Character Description"
        }
    }
}

const getCharacterById = async (id: string): Promise<Character> => {
    try {
        const character = await fetch(`https://hp-api.onrender.com/api/character/${id}`, {
            cache: 'force-cache'
        })
            .then(resp => resp.json())

        return character[0]

    } catch (error) {
        notFound()
    }

}

export default async function CharacterPage({ params }: Props) {

    const character = await getCharacterById(params.id)!;


    return (
        <div className="flex flex-col items-center w-full h-screen p-2 bg-gray-900">
            <Image src={character?.image ?? ''} width={250} height={100} alt={character?.name} className="rounded-md" />
            <p className="font-bold text-2xl flex mt-2 ml-2 text-white"> <IoArrowRedoSharp /> <span className="text-white">Name - {character?.name}</span></p>
            {character?.house && <p className="font-bold text-2xl flex mt-2 ml-2 text-white"> <IoArrowRedoSharp /> <span className="text-white">House - {character?.house}</span></p>}
            {character?.patronus && <p className="font-bold text-2xl flex mt-2 ml-2 text-white"> <IoArrowRedoSharp /> <span className="text-white">Patronus -  {character?.patronus}</span></p>}
            {character?.actor && <p className="font-bold text-2xl flex mt-2 ml-2 text-white"> <IoArrowRedoSharp /> <span className="text-white">Actor  -  {character?.actor}</span></p>}


            <Link href={'/dashboard/characters'} className="font-bold w-40 bg-red-400 text-center mt-2 p-2 rounded-lg hover:cursor-pointer hover:bg-blue-400 trannsition-all duration-500">Go Home</Link>
        </div>
    )
}